apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fbk-api-app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fbk-api-deployment
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 200Mi
        maxAllowed:
          cpu: 400m  # Adjust maxAllowed as necessary
          memory: 500Mi  # Adjust maxAllowed as necessary
        controlledResources: ["cpu", "memory"]
