apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
spec:
  capacity:
    storage: 5Gi                            # Define the storage capacity
  accessModes:
    - ReadWriteOnce                         # Access mode allows one node to mount at a time
  persistentVolumeReclaimPolicy: Retain     # Retain the volume after release
  hostPath:                                 # Example of using hostPath for storage
    path: /c/data                           # Path on the host machine