apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce            # Ensures the volume is mounted by a single pod at a time
  resources:
    requests:
      storage: 5Gi             # Define the required storage size